atm:
  cam.h0:
    frequency: monthly
    stream: cam.h0
    freq: MS
    time_bounds_dim: nbnd
    variable_category:
      3D:
        variable:
          - T
          - U
          - v
          - Q
          - Z3
        experiment:
      #    ssp370:
      #      chunks:
      #        time: 18
          historical:
            chunks:
              time: 18
      2D:
        variable:
          - FLNS
          - FLNSC
          - FLUT
          - FSNS
          - FSNSC
          - FSNTOA
          - ICEFRAC
          - LHFLX
          - PRECC
          - PRECL
          - PRECSC
          - PRECSL
          - PSL
          - SHFLX
          - TMQ
          - TREFHT
          - TREFHTMN
          - TREFHTMX
          - TS
        experiment:
          CTRL:
            chunks:
              time: 576

          RCP85:
            chunks:
              time: 576

          20C:
            chunks:
              time: 576
      